name: qhhub
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  velocity_x: ^4.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/images/

  fonts:
  - family: nunito
    fonts: 
      - asset: assets/fonts/nunito.ttf
  - family: nunito_Bold
    fonts: 
      - asset: assets/fonts/nunito_Bold.ttf

